Hashtable
KiK0S/hse_algo_hashtable pull request #1
Opened 2020-03-16 22:02 UTC by KiK0S

Submit id: 31571511.

2020-03-16 23:22 UTC, glebshp requested changes
Оставил комментарии по оформлению.

В целом выглядит хорошо, по смыслу кажется всё правильно, перечитаю внимательнее после правок.

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +    // Default number of cells.
Непонятно, что значит default? Думаю ты имел в виду стартовое количество клеток.

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +    static const size_t NUM_OF_CELLS;
лучше использовать constexpr

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +constexpr size_t HashMap<KeyType, ValueType, Hash>::NUM_OF_CELLS = 10;
А зачем это делать таким способом?

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +  public:
+ пустая строка перед public

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +    HashMap(const Hash& hash_function): hasher_(hash_function) {
все поля\методы\конструкторы принято отбивать пустой строкой

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +    // Returns number of elements in the map.
вот этот и два следующих комментария как раз скорее пример избыточности.

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +    /* Insert an element into the hash table_ by its key.
hash table_ -> hashtable

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +                if (size() * 4 < current_capacity_) {
константа 4 достойна быть где-то отдельно именованой

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +        iterator() {}
тоже всё отбить пустыми строками

2020-03-16 23:22 UTC, glebshp commented on hashtable.h
> +        const_iterator(const HashMap *outer, size_t cell=0, size_t positon=0): outer(outer), cell(cell), positon(positon) {
= отбить пробелами

2020-03-17 09:11 UTC, KiK0S commented on hashtable.h
> +constexpr size_t HashMap<KeyType, ValueType, Hash>::NUM_OF_CELLS = 10;
Инициализация внутри класса для static не компилилась на ЯК (локально такой вариант вроде как работал). При этом, если назвать переменную constexpr, то плюсы требуют моментальную инициализацию (то есть внутри класса), что для static не делается. В итоге я выбирал из следующих вариантов, которые компилились:
- Нестатичная переменная, инициализация в классе.
- Статичная константная переменная, инициализация constexpr вне класса, при этом объявление внутри класса как const.

2020-04-02 13:26 UTC, KiK0S commented
id of submit: 31961172

2020-04-02 13:29 UTC, KiK0S commented on hashtable.h
> +        const_iterator(const HashMap *outer, size_t cell=0, size_t positon=0): outer(outer), cell(cell), positon(positon) {
done

2020-04-02 13:29 UTC, KiK0S commented on hashtable.h
> +        iterator() {}
done

2020-04-02 13:29 UTC, KiK0S commented on hashtable.h
> +                if (size() * 4 < current_capacity_) {
done

2020-04-02 13:30 UTC, KiK0S commented on hashtable.h
> +                if (size() * 4 < current_capacity_) {
правда в комментариях не менял, но вроде там по смыслу так лучше

2020-04-02 13:30 UTC, KiK0S commented on hashtable.h
> +    /* Insert an element into the hash table_ by its key.
done

2020-04-02 13:31 UTC, KiK0S commented on hashtable.h
> +    // Returns number of elements in the map.
убрал

2020-04-02 13:31 UTC, KiK0S commented on hashtable.h
> +    HashMap(const Hash& hash_function): hasher_(hash_function) {
done

2020-04-02 13:31 UTC, KiK0S commented on hashtable.h
> +  public:
done

2020-04-02 13:32 UTC, KiK0S commented on hashtable.h
> +    // Default number of cells.
Написал чуть подробнее

2020-04-02 13:32 UTC, KiK0S commented on hashtable.h
> +    static const size_t NUM_OF_CELLS;
Написал в следующий комментарий

2020-04-02 13:39 UTC, KiK0S commented on hashtable.h
> +constexpr size_t HashMap<KeyType, ValueType, Hash>::NUM_OF_CELLS = 10;
Так, я сейчас еще раз поясню, чтобы точно-точно было понятно:
* `public static constexpr var = 10;` — идеально, но не компилится на ЯК (локально вроде ок)
* `public constexpr var = 10;` — работает, но не статичная
* `public static const var = 10;` — не уверен, работает или нет, но в любом случае не constexpr.

Для того, чтобы реализован был в итоге первый вариант (и это компилилось на ЯК), я делаю создаю `public static const var`, а инициализирую ее как `constexpr` — получается громоздко, но ровно то, что и было нужно. В общем-то, я могу инициализацию прикрутить как в варианте 1 (и это конфетка), но она просто на ЯК не соберется.

2020-04-02 13:40 UTC, KiK0S commented
id:31961741

2020-05-31 00:06 UTC, glebshp requested changes

2020-05-31 00:06 UTC, glebshp commented on hashtable.h
> +    HashMap(const HashMap& other): hasher_(other.hasher_), table_(other.table_), current_size_(other.current_size_), current_capacity_(other.current_capacity_) {}
слишком длинная строка, не читается

2020-05-31 00:06 UTC, glebshp commented on hashtable.h
> +    static const size_t NUM_OF_CELLS;
тогда уж MIN_NUM_OF_CELLS

2020-05-31 00:06 UTC, glebshp commented on hashtable.h
> +        if (size() > current_capacity_) {
Вот эту логику лучше унести в отдельный метод, который наводит порядок с размером. Если таблица слишком большая или слишком маленькая, то зовёт rebuild

2020-05-31 00:06 UTC, glebshp commented on hashtable.h
> +                std::vector<std::pair<const KeyType, ValueType>> new_vector;
название new_vector можно улучшить

2020-05-31 00:06 UTC, glebshp commented on hashtable.h
> +                for (size_t j = 0; j < i; j++) {
а что за интересный способ удаления из вектора, почему не вызвать метод erase, или не свопнуть с последним и сделать pop_back?

2020-05-31 00:06 UTC, glebshp commented on hashtable.h
> +        void fix() {
А какой смысл мы вкладываем в этот метод, когда и зачем он применяется?

2020-06-04 17:59 UTC, KiK0S commented on hashtable.h
> +    static const size_t NUM_OF_CELLS;
done

2020-06-04 18:01 UTC, KiK0S commented on hashtable.h
> +    HashMap(const HashMap& other): hasher_(other.hasher_), table_(other.table_), current_size_(other.current_size_), current_capacity_(other.current_capacity_) {}
разбил на две по двум последним аргументам. теперь влезает у меня в экран

2020-06-04 18:04 UTC, KiK0S commented on hashtable.h
> +                std::vector<std::pair<const KeyType, ValueType>> new_vector;
лучшее название --- название, которого нет! done

2020-06-04 18:04 UTC, KiK0S commented on hashtable.h
> +                for (size_t j = 0; j < i; j++) {
со смыслом. erase действительно приятнее. done

2020-06-04 19:38 UTC, KiK0S commented on hashtable.h
> +        if (size() > current_capacity_) {
done

2020-06-04 19:38 UTC, KiK0S commented on hashtable.h
> +        void fix() {
done

2020-06-04 19:42 UTC, KiK0S commented
Отрефакторил прошлые замечания. Что принципиально поменялось:
* Я делал странное удаление из вектора за счет неприятного поведения объекта `pair<const A, B>`. Он не хочет двигаться-меняться, поэтому его нормально получалось только добавлять-удалять. Для этого я просто создавал новый вектор копий, не добавляя в него плохой элемент.
* Теперь, чтобы проблем не было, я просто храню умные указатели на эти пары.

2020-06-04 19:43 UTC, KiK0S commented
id of submit: 33381426

2020-06-09 21:35 UTC, glebshp requested changes

2020-06-09 21:35 UTC, glebshp commented on hashtable.h
> +    // an iterator which points to first cell
Комментарий должен быть предложением, начинаться с большой буквы, заканчиваться точкой.

2020-06-09 21:35 UTC, glebshp commented on hashtable.h
> +      private:
Сначала приватный метод, потом приватное поле, при этом следует визуально их разделять ещё одним private:

2020-06-09 21:35 UTC, glebshp commented on hashtable.h
> +        void make_valid() {
а в чём смысл этой функции? либо приходи в телеграмм обсудить, либо давай удалим

2020-06-12 15:37 UTC, KiK0S commented
id of submit: 33458444

2020-06-19 21:47 UTC, KiK0S commented
id of submit: 33520113

2020-06-19 23:17 UTC, glebshp approved these changes

2020-06-19 23:21 UTC, merged